### ISSUE TITLE
publish to via homebrew

### ISSUE THREAD

**Issue by tcurdt** [apricote/hcloud-upload-image#56]
Since you are already using goreleaser it would be great if you could also publish to homebrew.
Even if just as a tap.

```
brews:
  - repository:
      owner: apricote
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/apricote/{{ .ProjectName }}
    description: |
      The description of the project
```
